name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env
        run: cp .env.example .env

      - name: Create tests .env
        run: cp __tests__/.env.test.example __tests__/.env.test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-contexts: |
            alpine=docker-image://alpine:3.16
          tags: myimage:latest

      # - name: Set up Docker
      #   uses: docker/setup-action@v2
      #   with:
      #     dockerfile: Dockerfile
      #     context: .

      - name: Build docker images
        run: docker build -t ramez-app .

      - name: Run docker images
        run: docker run -d -p 5000:5000 --name=ramez-app ramez-app

      - name: Clean up
        run: docker stop ramez-app || true
          docker rm ramez-app || true
          docker rmi ramez-app || true
